apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wtb48menr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wtb48menr-nodejs 
  name: wtb48menr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wtb48menr-nodejs 
